name: Deploy documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deply documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: './docs/build'
          doxyfile-path: './docs/Doxyfile'
        
